# Form implementation generated from reading ui file 'designer/dialogForWaiting.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(522, 300)
        Dialog.setStyleSheet("QDialog{\n"
"    background-color:#0A5209;\n"
"    border-radius : 10px;\n"
"}\n"
"\n"
"#headerTitle{\n"
"    font-size:28px;\n"
"    color : #FFFFFF;\n"
"    font-weight:bold;\n"
"}\n"
"\n"
"#headerParent{\n"
"    box-shadow : 5px 5px 5px black;\n"
"    border : 4px solid white;\n"
"\n"
"}\n"
"\n"
"#closeButton {\n"
"    background-color:transparent;\n"
"    \n"
"}\n"
"\n"
"#waitingText {\n"
"    color : #FFFFFF;\n"
"    font-weight:bold;\n"
"    font-size:30px;\n"
"    font-style:italic;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerParent = QtWidgets.QWidget(parent=Dialog)
        self.headerParent.setObjectName("headerParent")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.headerParent)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.headerTitle = QtWidgets.QLabel(parent=self.headerParent)
        self.headerTitle.setObjectName("headerTitle")
        self.horizontalLayout.addWidget(self.headerTitle, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.closeButton = QtWidgets.QPushButton(parent=self.headerParent)
        self.closeButton.setMaximumSize(QtCore.QSize(35, 35))
        self.closeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/x-circle.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.closeButton.setIcon(icon)
        self.closeButton.setIconSize(QtCore.QSize(32, 32))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.verticalLayout.addWidget(self.headerParent, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.widget_2 = QtWidgets.QWidget(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.widget_2)
        self.label.setMaximumSize(QtCore.QSize(150, 200))
        self.label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/free.svg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(20, 20, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_3.setMaximumSize(QtCore.QSize(150, 100))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/newPrefix/sab_animate.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.waitingText = QtWidgets.QLabel(parent=self.widget_2)
        self.waitingText.setWordWrap(True)
        self.waitingText.setObjectName("waitingText")
        self.verticalLayout_2.addWidget(self.waitingText, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.headerTitle.setText(_translate("Dialog", "Magoe Education"))
        self.waitingText.setText(_translate("Dialog", "Veuillez attendre svp..."))
