# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/modalPayementFrais.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_payementFrais(object):
    def setupUi(self, payementFrais):
        payementFrais.setObjectName("payementFrais")
        payementFrais.resize(621, 567)
        payementFrais.setStyleSheet(" #container{\n"
"    border:4px solid white;\n"
"    background-color:black;\n"
"    border-radius:7px;\n"
"    box-shadow: 6px 6px 7px red;\n"
"}\n"
"\n"
"#frameHeader{\n"
"    background-color:white;\n"
"}\n"
"\n"
"#frameHeader QLabel{\n"
"    color:black;\n"
"}\n"
"\n"
"#fermerModalPayement{\n"
"    background-color:red;\n"
"    border-radius:7px;\n"
"}\n"
"\n"
"QLabel{\n"
"    color:white;\n"
"}\n"
"\n"
"\n"
"#containerPayementContent{\n"
"    border-top:3px solid white;\n"
"}\n"
"\n"
"QPushButton,QLineEdit,QSpinBox,\n"
"QDateTimeEdit,QComboBox \n"
"{\n"
"    border-radius:3px;\n"
"    padding:2px;\n"
"    height:40px;\n"
"}\n"
"\n"
"QPushButton:focus,QLineEdit:focus,QSpinBox:focus,\n"
"QDateTimeEdit:focus,QComboBox:focus\n"
"{\n"
"    border :1px solid blue;\n"
"}\n"
"\n"
"#enregistrerPayementBtn{\n"
"    background-color:green;\n"
"    border-radius:5px;\n"
"    font-size:18px;\n"
"    color:white;\n"
"}\n"
"#enregistrerPayementBtn:hover{\n"
"    background-color:white;\n"
"    color:black;\n"
"    border:2px solid white;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(payementFrais)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.container = QtWidgets.QWidget(payementFrais)
        self.container.setObjectName("container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.container)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frameHeader = QtWidgets.QFrame(self.container)
        self.frameHeader.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameHeader.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameHeader.setObjectName("frameHeader")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameHeader)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frameHeader)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2 = QtWidgets.QLabel(self.frameHeader)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignVCenter)
        self.fermerModalPayement = QtWidgets.QPushButton(self.frameHeader)
        self.fermerModalPayement.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fermerModalPayement.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/x-square.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fermerModalPayement.setIcon(icon)
        self.fermerModalPayement.setIconSize(QtCore.QSize(32, 32))
        self.fermerModalPayement.setObjectName("fermerModalPayement")
        self.horizontalLayout.addWidget(self.fermerModalPayement)
        self.verticalLayout_2.addWidget(self.frameHeader, 0, QtCore.Qt.AlignTop)
        self.containerPayementContent = QtWidgets.QFrame(self.container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.containerPayementContent.sizePolicy().hasHeightForWidth())
        self.containerPayementContent.setSizePolicy(sizePolicy)
        self.containerPayementContent.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.containerPayementContent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.containerPayementContent.setObjectName("containerPayementContent")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.containerPayementContent)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.containerPayementContent)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.spinBox = QtWidgets.QSpinBox(self.frame)
        self.spinBox.setMinimumSize(QtCore.QSize(300, 0))
        self.spinBox.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        self.spinBox.setFont(font)
        self.spinBox.setMaximum(999999999)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_4 = QtWidgets.QFrame(self.containerPayementContent)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(300, 29))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_5.addWidget(self.lineEdit_2)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_2 = QtWidgets.QFrame(self.containerPayementContent)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_5 = QtWidgets.QFrame(self.containerPayementContent)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.comboBox = QtWidgets.QComboBox(self.frame_5)
        self.comboBox.setMinimumSize(QtCore.QSize(300, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.containerPayementContent)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.spinBox_2 = QtWidgets.QSpinBox(self.frame_6)
        self.spinBox_2.setMinimumSize(QtCore.QSize(300, 0))
        self.spinBox_2.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setMaximum(999999999)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_7.addWidget(self.spinBox_2)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_3 = QtWidgets.QFrame(self.containerPayementContent)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.frame_3)
        self.dateTimeEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.dateTimeEdit.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setMinimumDate(QtCore.QDate(2023, 8, 9))
        self.dateTimeEdit.setMinimumTime(QtCore.QTime(10, 12, 0))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalLayout_4.addWidget(self.dateTimeEdit)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.frame_7 = QtWidgets.QFrame(self.containerPayementContent)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.enregistrerPayementBtn = QtWidgets.QPushButton(self.frame_7)
        self.enregistrerPayementBtn.setMinimumSize(QtCore.QSize(300, 40))
        self.enregistrerPayementBtn.setMaximumSize(QtCore.QSize(300, 40))
        self.enregistrerPayementBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.enregistrerPayementBtn.setObjectName("enregistrerPayementBtn")
        self.horizontalLayout_8.addWidget(self.enregistrerPayementBtn)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.verticalLayout_2.addWidget(self.containerPayementContent)
        self.verticalLayout.addWidget(self.container)

        self.retranslateUi(payementFrais)
        QtCore.QMetaObject.connectSlotsByName(payementFrais)

    def retranslateUi(self, payementFrais):
        _translate = QtCore.QCoreApplication.translate
        payementFrais.setWindowTitle(_translate("payementFrais", "Dialog"))
        self.label.setText(_translate("payementFrais", "Payement pour :"))
        self.label_2.setText(_translate("payementFrais", "Guilavogui Foromo Pierre"))
        self.fermerModalPayement.setToolTip(_translate("payementFrais", "Fermer le modal"))
        self.label_3.setWhatsThis(_translate("payementFrais", "<html><head/><body><p><br/></p></body></html>"))
        self.label_3.setText(_translate("payementFrais", "Montant (Max : )"))
        self.label_6.setText(_translate("payementFrais", "Nom du remettant"))
        self.lineEdit_2.setPlaceholderText(_translate("payementFrais", "Ex : Guilavogui Father"))
        self.label_4.setText(_translate("payementFrais", "Nom du receveur"))
        self.lineEdit.setPlaceholderText(_translate("payementFrais", "Foromo Pierre Guilavogui"))
        self.label_7.setText(_translate("payementFrais", "Type de payement"))
        self.comboBox.setItemText(0, _translate("payementFrais", "Frais de Scolarité"))
        self.comboBox.setItemText(1, _translate("payementFrais", "Inscription"))
        self.comboBox.setItemText(2, _translate("payementFrais", "Réinscription"))
        self.label_8.setText(_translate("payementFrais", "Mode de payement"))
        self.label_5.setText(_translate("payementFrais", "Date de payement"))
        self.enregistrerPayementBtn.setText(_translate("payementFrais", "Valider le payement"))
import QSS_Resources_rc
